config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(articles_params)
    @article.save
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(articles_params)
    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def articles_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>Here are my articles</h1>

<% @articles.each do |article| %>
<ul>
  <li> <%if article.completed == true %>
    <p><i class="fas fa-check-square"></i> <%=link_to article.title, article_path(article.id)%>
    <% else %>
    <p><i class="fas fa-stop"></i> <%= link_to article.title, article_path(article.id)%>
    <% end %>
     <%= link_to article_path(article.id),
    method: :delete,
    data: { confirm: "Are you sure?" } do %>
    <i class="fas fa-trash-alt"></i>
    <% end %>
  </li>
</ul>
<% end %>

<p>   <i class="fas fa-plus"></i>  <%= link_to  'Add a new article', new_article_path %></p>

app/views/articles/new.html.erb
new.html.erb

app/views/articles/show.html.erb
<h1>:)</h1>

<h2><%= @article.title %></h2>
<p><%= @article.content %></p>

<p>
  <%= link_to 'Edit article', edit_path %>
</p>
<p>
  <%= link_to 'Back to my tasks', articles_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>